"""empty message

Revision ID: 1cbb13d5a1ac
Revises: ad9a7371fabb
Create Date: 2024-07-29 18:02:32.690079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cbb13d5a1ac'
down_revision: Union[str, None] = 'ad9a7371fabb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('history_buys_which_filial_fkey', 'history_buys', type_='foreignkey')
    op.drop_column('history_buys', 'which_filial')
    op.drop_column('history_buys', 'where_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_buys', sa.Column('where_to', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('history_buys', sa.Column('which_filial', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('history_buys_which_filial_fkey', 'history_buys', 'filials', ['which_filial'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
