"""empty message

Revision ID: 59badcf4f5c1
Revises: d106e92ac910
Create Date: 2024-07-31 13:59:35.546344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59badcf4f5c1'
down_revision: Union[str, None] = 'd106e92ac910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_abouts', 'type',
               existing_type=postgresql.ENUM('🚶 Olib ketish', '🚚 Dostavka', name='order_type'),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_abouts', 'type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('🚶 Olib ketish', '🚚 Dostavka', name='order_type'),
               existing_nullable=True)
    # ### end Alembic commands ###
