"""empty message

Revision ID: 700062be6bdc
Revises: 6eb4f9cd1c7f
Create Date: 2024-07-29 22:15:23.770793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700062be6bdc'
down_revision: Union[str, None] = '6eb4f9cd1c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('foods_menu_id_fkey', 'foods', type_='foreignkey')
    op.create_foreign_key(None, 'foods', 'menu', ['menu_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'foods', type_='foreignkey')
    op.create_foreign_key('foods_menu_id_fkey', 'foods', 'menu', ['menu_id'], ['id'])
    # ### end Alembic commands ###
