"""empty message

Revision ID: ad9a7371fabb
Revises: 3f76e9eeaa7a
Create Date: 2024-07-29 17:58:33.528621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9a7371fabb'
down_revision: Union[str, None] = '3f76e9eeaa7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_abouts', sa.Column('where_to', sa.String(), nullable=True))
    op.add_column('order_abouts', sa.Column('which_filial', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_abouts', 'which_filial')
    op.drop_column('order_abouts', 'where_to')
    # ### end Alembic commands ###
