"""empty message

Revision ID: cb3ace8b5ce7
Revises: 59badcf4f5c1
Create Date: 2024-07-31 21:47:19.179112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb3ace8b5ce7'
down_revision: Union[str, None] = '59badcf4f5c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_products', sa.Column('lang', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_products', 'lang')
    # ### end Alembic commands ###
