from . import start
from . import main_buttons
from . import help
from . import order
from . import main_menu
from . import menu
from . import register
from . import admin_functions
from . import echo
from . import main_inline_keyboards